---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nodejs-argo-app
  namespace: rhdh-projects
  labels:
    argocd/app-name: my-nodejs-demo-argo
  annotations:
    argocd/app-name: my-nodejs-demo-argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/rhdhdemo/my-nodejs-demo.git
    targetRevision: HEAD
    path: ./helm/app
  destination:
    server: https://kubernetes.default.svc
    namespace: rhdh-projects
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strateg